/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MorphsRouteImport } from './routes/Morphs'
import { Route as LogbookRouteImport } from './routes/Logbook'
import { Route as HomeRouteImport } from './routes/Home'
import { Route as CareGuideRouteImport } from './routes/Care-guide'
import { Route as BreedingRouteImport } from './routes/Breeding'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserProfileRouteImport } from './routes/_user/profile'
import { Route as PublicUnsubscribeRouteImport } from './routes/_public/unsubscribe'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicPostsRouteImport } from './routes/_public/posts'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetLinkRouteImport } from './routes/_auth/reset-link'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AdminPostsRouteRouteImport } from './routes/admin/posts/route'
import { Route as AdminTagsIndexRouteImport } from './routes/admin/tags/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminCommentsIndexRouteImport } from './routes/admin/comments/index'
import { Route as PublicPostSlugRouteImport } from './routes/_public/post/$slug'
import { Route as AdminPostsEditIdRouteImport } from './routes/admin/posts/edit.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MorphsRoute = MorphsRouteImport.update({
  id: '/Morphs',
  path: '/Morphs',
  getParentRoute: () => rootRouteImport,
} as any)
const LogbookRoute = LogbookRouteImport.update({
  id: '/Logbook',
  path: '/Logbook',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/Home',
  path: '/Home',
  getParentRoute: () => rootRouteImport,
} as any)
const CareGuideRoute = CareGuideRouteImport.update({
  id: '/Care-guide',
  path: '/Care-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedingRoute = BreedingRouteImport.update({
  id: '/Breeding',
  path: '/Breeding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRouteRoute,
} as any)
const PublicUnsubscribeRoute = PublicUnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPostsRoute = PublicPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetLinkRoute = AuthResetLinkRouteImport.update({
  id: '/reset-link',
  path: '/reset-link',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminPostsRouteRoute = AdminPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTagsIndexRoute = AdminTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsIndexRoute = AdminCommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicPostSlugRoute = PublicPostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminPostsEditIdRoute = AdminPostsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/Breeding': typeof BreedingRoute
  '/Care-guide': typeof CareGuideRoute
  '/Home': typeof HomeRoute
  '/Logbook': typeof LogbookRoute
  '/Morphs': typeof MorphsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-link': typeof AuthResetLinkRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/posts': typeof PublicPostsRoute
  '/search': typeof PublicSearchRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/profile': typeof UserProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Breeding': typeof BreedingRoute
  '/Care-guide': typeof CareGuideRoute
  '/Home': typeof HomeRoute
  '/Logbook': typeof LogbookRoute
  '/Morphs': typeof MorphsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-link': typeof AuthResetLinkRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/posts': typeof PublicPostsRoute
  '/search': typeof PublicSearchRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/profile': typeof UserProfileRoute
  '/admin': typeof AdminIndexRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/comments': typeof AdminCommentsIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tags': typeof AdminTagsIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/Breeding': typeof BreedingRoute
  '/Care-guide': typeof CareGuideRoute
  '/Home': typeof HomeRoute
  '/Logbook': typeof LogbookRoute
  '/Morphs': typeof MorphsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-link': typeof AuthResetLinkRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_public/posts': typeof PublicPostsRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/unsubscribe': typeof PublicUnsubscribeRoute
  '/_user/profile': typeof UserProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/post/$slug': typeof PublicPostSlugRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/Breeding'
    | '/Care-guide'
    | '/Home'
    | '/Logbook'
    | '/Morphs'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/admin/posts'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/posts'
    | '/search'
    | '/unsubscribe'
    | '/profile'
    | '/admin/'
    | '/post/$slug'
    | '/admin/comments/'
    | '/admin/media/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/admin/posts/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Breeding'
    | '/Care-guide'
    | '/Home'
    | '/Logbook'
    | '/Morphs'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/posts'
    | '/search'
    | '/unsubscribe'
    | '/profile'
    | '/admin'
    | '/post/$slug'
    | '/admin/comments'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/posts/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/_user'
    | '/admin'
    | '/Breeding'
    | '/Care-guide'
    | '/Home'
    | '/Logbook'
    | '/Morphs'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/admin/posts'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-link'
    | '/_auth/verify-email'
    | '/_public/posts'
    | '/_public/search'
    | '/_public/unsubscribe'
    | '/_user/profile'
    | '/admin/'
    | '/_public/post/$slug'
    | '/admin/comments/'
    | '/admin/media/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/admin/posts/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BreedingRoute: typeof BreedingRoute
  CareGuideRoute: typeof CareGuideRoute
  HomeRoute: typeof HomeRoute
  LogbookRoute: typeof LogbookRoute
  MorphsRoute: typeof MorphsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Morphs': {
      id: '/Morphs'
      path: '/Morphs'
      fullPath: '/Morphs'
      preLoaderRoute: typeof MorphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Logbook': {
      id: '/Logbook'
      path: '/Logbook'
      fullPath: '/Logbook'
      preLoaderRoute: typeof LogbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Care-guide': {
      id: '/Care-guide'
      path: '/Care-guide'
      fullPath: '/Care-guide'
      preLoaderRoute: typeof CareGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Breeding': {
      id: '/Breeding'
      path: '/Breeding'
      fullPath: '/Breeding'
      preLoaderRoute: typeof BreedingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_public/unsubscribe': {
      id: '/_public/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof PublicUnsubscribeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/posts': {
      id: '/_public/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PublicPostsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-link': {
      id: '/_auth/reset-link'
      path: '/reset-link'
      fullPath: '/reset-link'
      preLoaderRoute: typeof AuthResetLinkRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tags/': {
      id: '/admin/tags/'
      path: '/tags'
      fullPath: '/admin/tags/'
      preLoaderRoute: typeof AdminTagsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments/': {
      id: '/admin/comments/'
      path: '/comments'
      fullPath: '/admin/comments/'
      preLoaderRoute: typeof AdminCommentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/post/$slug': {
      id: '/_public/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PublicPostSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/posts/edit/$id': {
      id: '/admin/posts/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/posts/edit/$id'
      preLoaderRoute: typeof AdminPostsEditIdRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetLinkRoute: typeof AuthResetLinkRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetLinkRoute: AuthResetLinkRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicPostsRoute: typeof PublicPostsRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicUnsubscribeRoute: typeof PublicUnsubscribeRoute
  PublicPostSlugRoute: typeof PublicPostSlugRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicPostsRoute: PublicPostsRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicUnsubscribeRoute: PublicUnsubscribeRoute,
  PublicPostSlugRoute: PublicPostSlugRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserProfileRoute: typeof UserProfileRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserProfileRoute: UserProfileRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AdminPostsRouteRouteChildren {
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminPostsEditIdRoute: typeof AdminPostsEditIdRoute
}

const AdminPostsRouteRouteChildren: AdminPostsRouteRouteChildren = {
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminPostsEditIdRoute: AdminPostsEditIdRoute,
}

const AdminPostsRouteRouteWithChildren = AdminPostsRouteRoute._addFileChildren(
  AdminPostsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminPostsRouteRoute: typeof AdminPostsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCommentsIndexRoute: typeof AdminCommentsIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTagsIndexRoute: typeof AdminTagsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPostsRouteRoute: AdminPostsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCommentsIndexRoute: AdminCommentsIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTagsIndexRoute: AdminTagsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BreedingRoute: BreedingRoute,
  CareGuideRoute: CareGuideRoute,
  HomeRoute: HomeRoute,
  LogbookRoute: LogbookRoute,
  MorphsRoute: MorphsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
